version: '3'

services:
  db-api-pgd:
    image: postgres:11
    ports:
      - "5432"
    volumes:
        - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  web:
    image: api-pgd:latest
    command:
      bash -c 'while !</dev/tcp/db-api-pgd/5432; do echo "Waiting for database to start..."; sleep 1; done; uvicorn api:app --host 0.0.0.0 --port 5057 --reload'
    ports:
      - "5057:5057"
    volumes:
        - ./:/home/api-pgd
    depends_on:
      - db-api-pgd
    build: ./
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-api-pgd:5432/${POSTGRES_DB}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data/servers.json:/pgadmin4/servers.json
      - ./pgadmin_data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db-api-pgd
