version: '3'

services:
  db-api-pgd:
    image: postgres:15
    ports:
      - "5432"
    volumes:
        - ./database:/var/lib/postgresql/data
        - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_pgd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api_pgd"]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    build: ./
    # image: api-pgd:latest
    depends_on:
      db-api-pgd:
        condition: service_healthy
    ports:
      - "5057:5057"
    volumes:
        - ./:/home/api-pgd
    environment:
      WEB_URI_SCHEME: http
      WEB_HOST_NAME: web
      WEB_PORT: 5057
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg://postgres:postgres@db-api-pgd:5432/api_pgd
      MAIL_USERNAME: api-pgd@email-provider.gov.br
      MAIL_FROM: api-pgd@email-provider.gov.br
      MAIL_PORT: "25"
      MAIL_SERVER: smtp.email-provider.gov.br
      MAIL_FROM_NAME: API PGD
      MAIL_PASSWORD: ""
      FIEF_BASE_TENANT_URL: http://fief:8000
      FIEF_CLIENT_ID: FNmytF0epvJxHKaUYEDEUVX-TchhOpkRTB01Y2dKY08
      FIEF_CLIENT_SECRET: D2GfMzCmlpwgBTmwQ1_2CUSMSrEWrHE7CIOHwSp0a-Y
      FIEF_MAIN_ADMIN_API_KEY: sOMe2rtZosMYylkWFAK624YVPiZjnLCos05GnX_yfA0
      FIEF_MAIN_USER_EMAIL: test-pgd@nonexisting.gov.br
    command:
      ./run_after_db.py "cd src && uvicorn api:app --host 0.0.0.0 --port 5057 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5057"]
      interval: 10s
      timeout: 5s
      retries: 3
  fief:
    build:
      context: ./
      dockerfile: Dockerfile.fief
    # image: ghcr.io/fief-dev/fief:latest
    depends_on:
      db-api-pgd:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      CLIENT_REDIRECT_URI_SSL_REQUIRED: False
      SECRET: Ioy2a6waEN6g2knCBbe0G23obQ2wl8_0-H9WyuQv0Ra7oj6_yK4IF9UWMUmSyEQ9DbIZX6XlQ7xCVIpPWQbSgg
      FIEF_CLIENT_ID: FNmytF0epvJxHKaUYEDEUVX-TchhOpkRTB01Y2dKY08
      FIEF_CLIENT_SECRET: D2GfMzCmlpwgBTmwQ1_2CUSMSrEWrHE7CIOHwSp0a-Y
      ENCRYPTION_KEY: u-yug5v5SvQQkNmgM5NLXNRvWbWpUJAdYaSETTwQ3rk=
      FIEF_MAIN_ADMIN_API_KEY: sOMe2rtZosMYylkWFAK624YVPiZjnLCos05GnX_yfA0
      PORT: "8000"
      ROOT_DOMAIN: fief:8000
      FIEF_DOMAIN: fief:8000
      FIEF_MAIN_USER_EMAIL: test-pgd@nonexisting.gov.br
      FIEF_MAIN_USER_PASSWORD: 123456*abcdef
      CSRF_COOKIE_SECURE: False
      SESSION_DATA_COOKIE_SECURE: False
      USER_LOCALE_COOKIE_SECURE: False
      LOGIN_HINT_COOKIE_SECURE: False
      LOGIN_SESSION_COOKIE_SECURE: False
      REGISTRATION_SESSION_COOKIE_SECURE: False
      SESSION_COOKIE_SECURE: False
      FIEF_ADMIN_SESSION_COOKIE_SECURE: False
      DATABASE_TYPE: POSTGRESQL
      DATABASE_HOST: db-api-pgd
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: fief
      TELEMETRY_ENABLED: False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://fief:8000/login"]
      interval: 10s
      timeout: 5s
      retries: 3
