version: '3'

services:
  db-api-pgd:
    image: postgres:15
    ports:
      - "5432"
    volumes:
        - ./database:/var/lib/postgresql/data
        - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    build: ./
    # image: api-pgd:latest
    depends_on:
      db-api-pgd:
        condition: service_healthy
    ports:
      - "5057:5057"
    volumes:
        - ./:/home/api-pgd
    environment:
      - WEB_URI_SCHEME=${WEB_URI_SCHEME}
      - WEB_HOST_NAME=${WEB_HOST_NAME}
      - WEB_PORT=5057
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-api-pgd:5432/${POSTGRES_DB}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FIEF_BASE_TENANT_URL=${FIEF_BASE_TENANT_URL}
      - FIEF_CLIENT_ID=${FIEF_CLIENT_ID}
      - FIEF_CLIENT_SECRET=${FIEF_CLIENT_SECRET}
      - FIEF_MAIN_ADMIN_API_KEY=${FIEF_MAIN_ADMIN_API_KEY}
      - FIEF_MAIN_USER_EMAIL=${FIEF_MAIN_USER_EMAIL}
    command:
      ./run_after_db.py "cd src && uvicorn api:app --host 0.0.0.0 --port 5057 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5057"]
      interval: 10s
      timeout: 5s
      retries: 3
  fief:
    build:
      context: ./
      dockerfile: Dockerfile.fief
    # image: ghcr.io/fief-dev/fief:latest
    depends_on:
      db-api-pgd:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - SECRET=${SECRET}
      - FIEF_CLIENT_ID=${FIEF_CLIENT_ID}
      - FIEF_CLIENT_SECRET=${FIEF_CLIENT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FIEF_MAIN_ADMIN_API_KEY=${FIEF_MAIN_ADMIN_API_KEY}
      - PORT=8000
      - ROOT_DOMAIN=fief:8000
      - FIEF_DOMAIN=fief:8000
      - FIEF_MAIN_USER_EMAIL=${FIEF_MAIN_USER_EMAIL}
      - FIEF_MAIN_USER_PASSWORD=${FIEF_MAIN_USER_PASSWORD}
      - CSRF_COOKIE_SECURE=False
      - SESSION_DATA_COOKIE_SECURE=False
      - USER_LOCALE_COOKIE_SECURE=False
      - LOGIN_HINT_COOKIE_SECURE=False
      - LOGIN_SESSION_COOKIE_SECURE=False
      - REGISTRATION_SESSION_COOKIE_SECURE=False
      - SESSION_COOKIE_SECURE=False
      - FIEF_ADMIN_SESSION_COOKIE_SECURE=False
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_HOST=db-api-pgd
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${FIEF_DB}
      - TELEMETRY_ENABLED=False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://fief:8000/login"]
      interval: 10s
      timeout: 5s
      retries: 3
