name: Docker Image Build & CI Tests

on:
  push:
    branches:
      - main
      - v0.2.x-alpha
    tags: [ tmp-rerun ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    name: build and test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create pgadmin_data volume folder
      run: sudo mkdir -p pgadmin_data && sudo chown -R 5050:5050 ./pgadmin_data/
    - name: Initialize environment variables
      run: ./init/load_fief_env.sh --user-email api-pgd@nonexisting.gov.br --user-password=123456*abcdef
    - name: Run all service containers
      run: docker-compose up -d
    - name: Configure Fief at runtime
      run: make fief-configure-instance
    - name: run tests
      run: make tests
