name: Docker Image Build & CI Tests

on:
  push:
    branches: [ main ]
    tags: [ tmp-rerun ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    name: build and test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag api-pgd
    - name: Create pgadmin_data volume
      run: sudo mkdir -p pgadmin_data && sudo chown -R 5050:5050 ./pgadmin_data/
    - name: Run docker-compose
      run: docker-compose up -d
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: api_pgd
    - name: run tests
      run: docker exec api-pgd_web_1 /bin/bash -c "./run_after_db.py \"pytest tests/\""
